# @generated by scripts/vision-v2-contracts/generate-bundle.ts
from __future__ import annotations

import json
from pathlib import Path
from urllib.parse import parse_qsl, urlparse
from typing import Any, Literal, Union

from jsonschema import Draft202012Validator, FormatChecker
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator

PROTOCOL = "vem.vision.v2"
CONTRACT_BUNDLE_VERSION = "1"

# The JSON Schema is generated from the VEM Zod source and is the semantic
# authority. These strict Pydantic models give Vision typed boundary values;
# parse_message first applies that exact generated schema to avoid a hand-kept
# Python validation mirror drifting from the wire contract.
_SCHEMA_PATH = Path(__file__).resolve().parents[1] / "vision-v2.schema.json"
_SCHEMA = json.loads(_SCHEMA_PATH.read_text(encoding="utf-8"))
_SCHEMA_VALIDATOR = Draft202012Validator(_SCHEMA, format_checker=FormatChecker())

class StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)

class TokenizedLoopbackReferenceModel(StrictModel):
    @field_validator("reference", check_fields=False)
    @classmethod
    def validate_tokenized_loopback_reference(cls, value: StrictStr) -> StrictStr:
        parsed = urlparse(value)
        first_token = next(
            (token for key, token in parse_qsl(parsed.query, keep_blank_values=True) if key == "token"),
            None,
        )
        if (
            parsed.scheme not in {"http", "https"}
            or parsed.hostname not in {"127.0.0.1", "localhost", "::1"}
            or parsed.username is not None
            or parsed.password is not None
            or not first_token
        ):
            raise ValueError("reference must be a tokenized loopback URL")
        return value

class GarmentSource(TokenizedLoopbackReferenceModel):
    assetId: StrictStr
    reference: StrictStr
    digest: StrictStr
    contentType: Literal["image/png"]
    byteSize: StrictInt
    template: Literal["tshirt_short_sleeve", "tshirt_long_sleeve"]

class ResultReference(TokenizedLoopbackReferenceModel):
    reference: StrictStr
    digest: StrictStr
    contentType: Literal["image/png"]
    byteSize: StrictInt
    width: StrictInt
    height: StrictInt

class HelloPayload(StrictModel):
    clientRole: Literal["machine"]
    machineCode: StrictStr | None = None
    contractDigest: StrictStr
    capabilities: list[StrictStr]

class ReadyPayload(StrictModel):
    serverName: StrictStr
    serverVersion: StrictStr
    contractDigest: StrictStr
    cameraReady: StrictBool
    fastReady: StrictBool
    visionBusinessReady: StrictBool
    capabilities: list[StrictStr]

class FastAttemptStartPayload(StrictModel):
    attemptId: StrictStr
    mode: Literal["fast"]
    variantId: StrictStr
    garment: GarmentSource

class AttemptAcceptedPayload(StrictModel):
    attemptId: StrictStr
    mode: Literal["fast"]

class AttemptProgressPayload(StrictModel):
    attemptId: StrictStr
    stage: Literal["generating"]

class AttemptCompletedPayload(StrictModel):
    attemptId: StrictStr
    result: ResultReference

class VisionV2Envelope(StrictModel):
    protocol: Literal["vem.vision.v2"]
    type: Literal["vision.hello", "vision.ready", "vision.try_on.attempt.start", "vision.try_on.attempt.accepted", "vision.try_on.attempt.progress", "vision.try_on.attempt.completed"]
    messageId: StrictStr
    timestamp: StrictStr
    payload: dict[str, Any]

Payload = Union[HelloPayload, ReadyPayload, FastAttemptStartPayload, AttemptAcceptedPayload, AttemptProgressPayload, AttemptCompletedPayload]

_PAYLOADS = {
    "vision.hello": HelloPayload,
    "vision.ready": ReadyPayload,
    "vision.try_on.attempt.start": FastAttemptStartPayload,
    "vision.try_on.attempt.accepted": AttemptAcceptedPayload,
    "vision.try_on.attempt.progress": AttemptProgressPayload,
    "vision.try_on.attempt.completed": AttemptCompletedPayload,
}

def parse_message(value: Any) -> VisionV2Envelope:
    error = next(iter(_SCHEMA_VALIDATOR.iter_errors(value)), None)
    if error is not None:
        raise ValueError(f"invalid {PROTOCOL} message: {error.message}")
    envelope = VisionV2Envelope.model_validate(value)
    _PAYLOADS[envelope.type].model_validate(envelope.payload)
    return envelope
